SELECT * FROM SALE;
SELECT COUNT(*) FROM SALE;
SELECT SUM (SALES) AS TOTAL_SALES FROM SALE;
SELECT DISTINCT (YEAR_ID) AS TOTAL_YEARS FROM SALE;
SELECT SUM(QUANTITYORDERED)AS TOTAL_QUANTITY FROM SALE;
SELECT DISTINCT(PRODUCTLINE) AS PRODUCT_LINES FROM SALE;
SELECT DISTINCT(COUNTRY)AS COUNTRIES FROM SALE;
SELECT DISTINCT(STATUS) AS STATUS FROM SALE;
SELECT DISTINCT STATE AS STATES 
FROM SALE 
ORDER BY STATES ASC;
SELECT DISTINCT(DEALSIZE) AS DEAL_SIZES FROM SALE;
SELECT DISTINCT(MONTH_ID) FROM SALE;

---.... TOTAL SALES BY MONTHLY, QUATERLY, YEARLY ....---

SELECT DISTINCT 
YEAR_ID AS YEAR,
QTR_ID AS QUATER,
MONTH_ID AS MONTH,
SUM(SALES) AS TOTAL_SALES
FROM SALE
GROUP BY YEAR_ID,QTR_ID,MONTH_ID
ORDER BY YEAR, MONTH ASC;

SELECT 
YEAR_ID AS YEAR,
QTR_ID AS QUATER,
SUM(SALES) AS TOTAL_SALES
FROM SALE
GROUP BY YEAR_ID, QTR_ID  
ORDER BY YEAR_ID, QTR_ID ASC;

SELECT 
  YEAR_ID AS "YEAR",
  SUM(SALES) AS TOTAL_SALES
FROM 
  SALE
GROUP BY 
  YEAR_ID
ORDER BY 
  "YEAR" ASC;
  
---.... REPEAT_CUSTOMERS....---  
  
SELECT CUSTOMERNAME, COUNT(*) AS CountOfCustomers
FROM SALE
GROUP BY CUSTOMERNAME
ORDER BY CountOfCustomers ASC;

---PRODUCT ANALYSIS....---
 ---.... SALES BY QUANTITY, PRODUCTS AND YEAR....---

SELECT
    SUM(QUANTITYORDERED) AS TOTAL_QUANTITY,
    SUM(SALES) AS TOTAL_SALES
FROM
    SALE;
    
 SELECT 
 YEAR_ID AS YEAR,
 SUM(QUANTITYORDERED) AS QUANTITY,
 SUM(SALES) AS TOTAL_SALES
 FROM SALE
 GROUP BY YEAR_ID
 ORDER BY YEAR ASC;
 
 SELECT 
 YEAR_ID AS YEAR,
 PRODUCTLINE AS PRODUCT_LINE,
 SUM(QUANTITYORDERED) AS QUANTITY,
 SUM(SALES) AS TOTAL_SALES
 FROM SALE
 GROUP BY YEAR_ID,PRODUCTLINE
 ORDER BY YEAR,QUANTITY ASC;
 
 ---....HIGHEST SELLING PRODUCTS....---
 
 SELECT 
    YEAR_ID,
    PRODUCTLINE AS PRODUCT,
    SUM(QUANTITYORDERED) AS QUANTITY,
    SUM(SALES) AS TOTAL_SALES
FROM 
    SALE
GROUP BY 
    YEAR_ID, PRODUCTLINE
HAVING 
    SUM(QUANTITYORDERED) > 4500
ORDER BY 
    YEAR_ID ASC;
    
---.... PRODUCTS CONTRIBUTING TO THE TOTAL NUMBER OF SALES....---

    SELECT 
    PRODUCTLINE AS Product_Category,
    SUM(SALES) AS Total_Sales,
    ROUND((SUM(SALES) / (SELECT SUM(SALES) FROM SALE)) * 100, 2) AS Sales_Contribution_Percentage
FROM 
    SALE
GROUP BY 
    PRODUCTLINE
ORDER BY 
    Total_Sales DESC;
    
    
---.... DEMOGRAPHIC ANALYSIS....---
 ---.... SALES BY COUNTRIES AND STATES ....---
 
 
 SELECT YEAR_ID AS YEAR,
 SUM(SALES) AS TOTAL_SALES,
 COUNTRY
 FROM SALE
 GROUP BY  YEAR_ID,COUNTRY
 ORDER BY YEAR, TOTAL_SALES ASC;
 
 SELECT 
 YEAR_ID AS YEAR,
 COUNTRY,
 STATE,
 SUM(SALES) AS TOTAL_SALES
 FROM SALE
 GROUP BY YEAR_ID, STATE, COUNTRY
 ORDER BY YEAR, COUNTRY ASC;
 
 ---....TOTAL SALES BY PERCENTAGE....---
 SELECT 
 COUNTRY,
 ROUND ((SUM(SALES) / (SELECT SUM(SALES) FROM SALE)) *100, 2) AS TOTAL_SALES_BY_PERCENTAGE
 FROM SALE
 GROUP BY COUNTRY
 ORDER BY TOTAL_SALES_BY_PERCENTAGE DESC;
  
 
 ---.... THE STATUS OF ORDERS....---
 
SELECT STATUS, COUNT(*) AS Status_Count
FROM SALE
GROUP BY STATUS;






    
    
    






    










 


